name: EAS Build

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]  # Auto trigger on push to main

jobs:
  eas-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        run: eas whoami || eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build Android App
        run: eas build --platform android --non-interactive
